default:
        address: '127.0.0.1'
        port: 9501
        model: SWOOLE_PROCESS
        socket_type: SWOOLE_SOCK_TCP
        setting:
            reactor_num: 4
            worker_num: 8
            max_request: 1
            daemonize: 0
            log_file: !env swoole.log.path
            log_level: !env swoole.log.level
            dispatch_mode: 3
            heartbeat_idle_time: 10
            heartbeat_check_interval: 5
            open_eof_check: true
            package_eof: !php "\r\n"
